<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="5" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2018-12-17T08:44:10Z" name="Default suite" finished-at="2018-12-17T08:44:11Z" duration-ms="1674">
    <groups>
    </groups>
    <test started-at="2018-12-17T08:44:10Z" name="Default test" finished-at="2018-12-17T08:44:11Z" duration-ms="1674">
      <class name="qgtest.Scene5">
        <test-method signature="login()[pri:0, instance:qgtest.Scene5@593aaf41]" started-at="2018-12-17T08:44:10Z" name="login" finished-at="2018-12-17T08:44:11Z" duration-ms="1218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method signature="addresslist()[pri:1, instance:qgtest.Scene5@593aaf41]" started-at="2018-12-17T08:44:11Z" name="addresslist" finished-at="2018-12-17T08:44:11Z" duration-ms="112" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [success] but found [请重新登录]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [success] but found [请重新登录]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at qgtest.Scene5.addresslist(Scene5.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addresslist -->
        <test-method signature="addressnew()[pri:2, instance:qgtest.Scene5@593aaf41]" started-at="2018-12-17T08:44:11Z" name="addressnew" finished-at="2018-12-17T08:44:11Z" duration-ms="92" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- addressnew -->
        <test-method signature="fee()[pri:3, instance:qgtest.Scene5@593aaf41]" started-at="2018-12-17T08:44:11Z" name="fee" finished-at="2018-12-17T08:44:11Z" duration-ms="90" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- fee -->
        <test-method signature="submit()[pri:4, instance:qgtest.Scene5@593aaf41]" started-at="2018-12-17T08:44:11Z" name="submit" finished-at="2018-12-17T08:44:11Z" duration-ms="110" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submit -->
      </class> <!-- qgtest.Scene5 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
